CoreProjectRole/Controllers/MyHomeController.cs
using CoreProjectRole.Data;
using CoreProjectRole.Models;
using CoreProjectRole.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreProjectRole.Controllers
{
    public class MyHomeController : Controller
    {
        
            private readonly ApplicationDbContext _context;
            private readonly IWebHostEnvironment _hostEnvironment;

            public MyHomeController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
            {
                _context = context;
                _hostEnvironment = hostEnvironment;
            }
            public IActionResult Index(int? id)
            {
                var ctx = _context;

                var categoryWiseProductQty = from p in ctx.ProductA
                                             group p by p.CategoryId into g
                                             select new
                                             {
                                                 g.FirstOrDefault().CategoryId,
                                                 Qty = g.Sum(s => s.Quantity)
                                             };
                var listCategory = (from c in ctx.Categories
                                    join cwpq in categoryWiseProductQty on c.CategoryId equals cwpq.CategoryId
                                    select new VmCategory
                                    {
                                        CategoryName = c.CategoryName,
                                        CategoryId = cwpq.CategoryId,
                                        Quantity = cwpq.Qty
                                    }).ToList();
                var listProduct = (from p in ctx.ProductA
                                   join c in ctx.Categories on p.CategoryId equals c.CategoryId
                                   where p.CategoryId == id
                                   select new VmProduct
                                   {
                                       CategoryId = p.CategoryId,
                                       CategoryName = c.CategoryName,
                                       ExpireDate = p.ExpireDate,
                                       ImagePath = p.ImagePath,
                                       Price = p.Price,
                                       ProductId = p.ProductId,
                                       ProductName = p.ProductName,
                                       Quantity = p.Quantity
                                   }).ToList();

                var oCategoryWiseProduct = new VmCategoryWiseProduct();
                oCategoryWiseProduct.CategoryList = listCategory;
                oCategoryWiseProduct.ProductList = listProduct;
                oCategoryWiseProduct.CategoryId = listProduct.Count > 0 ? listProduct[0].CategoryId : 0;
                oCategoryWiseProduct.CategoryName = listProduct.Count > 0 ? listProduct[0].CategoryName : "";

                return View(oCategoryWiseProduct);
            }

            public IActionResult Create()
            {
                var model = new VmProductCategory();
                var ctx = _context;
                model.CategoryList = ctx.Categories.ToList();
                return View(model);
            }

            [HttpPost]
            public async Task<IActionResult> Create(Category model, string[] ProductName, decimal[] Price, int[] Quantity, DateTime[] ExpireDate, IFormFile[] imgFile)
            {
                var ctx = _context;
                var oCatetory = (from c in ctx.Categories where c.CategoryName == model.CategoryName.Trim() select c).FirstOrDefault();
                if (oCatetory == null)
                {
                    ctx.Categories.Add(model);
                    ctx.SaveChanges();
                }
                else
                {
                    model.CategoryId = oCatetory.CategoryId;
                }

                var listProduct = new List<ProductSPA>();
                for (int i = 0; i < ProductName.Length; i++)
                {
                    string imgPath = "";
                    if (imgFile[i] != null && imgFile[i].Length > 0)
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        var fileName = Path.GetFileName(imgFile[i].FileName);
                        string path = Path.Combine(wwwRootPath + "/uploads/", fileName);
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await imgFile[i].CopyToAsync(fileStream);
                        }

                        imgPath = "/uploads/" + imgFile[i].FileName;
                    }

                    var newProduct = new ProductSPA();
                    newProduct.ProductName = ProductName[i];
                    newProduct.Quantity = Quantity[i];
                    newProduct.Price = Price[i];
                    newProduct.ExpireDate = ExpireDate[i];
                    newProduct.ImagePath = imgPath;
                    newProduct.Quantity = Quantity[i];
                    newProduct.CategoryId = model.CategoryId;
                    listProduct.Add(newProduct);
                }
                ctx.ProductA.AddRange(listProduct);
                ctx.SaveChanges();

                return RedirectToAction("Index");
            }

            public IActionResult Edit(int id)
            {
                var ctx = _context;
                var oProduct = (from p in ctx.ProductA
                                join c in ctx.Categories on p.CategoryId equals c.CategoryId
                                where p.ProductId == id
                                select new VmProduct
                                {
                                    CategoryId = p.CategoryId,
                                    CategoryName = c.CategoryName,
                                    ExpireDate = p.ExpireDate,
                                    ImagePath = p.ImagePath,
                                    Price = p.Price,
                                    ProductId = p.ProductId,
                                    ProductName = p.ProductName,
                                    Quantity = p.Quantity
                                }).FirstOrDefault();
                oProduct.CategoryList = ctx.Categories.ToList(); // for showing category list in view
                return View(oProduct);
            }

            [HttpPost]
            public async Task<IActionResult> Edit(VmProduct model)
            {
                var ctx = _context;

                string imgPath = "";
                if (model.ImgFile != null && model.ImgFile.Length > 0)
                {
                    //var fileName = Path.GetFileName(model.ImgFile.FileName);
                    //string fileLocation = Path.Combine(
                    //    Server.MapPath("~/uploads"), fileName);
                    //model.ImgFile.SaveAs(fileLocation);
                    string wwwRootPath = _hostEnvironment.WebRootPath;
                    var fileName = Path.GetFileName(model.ImgFile.FileName);
                    string path = Path.Combine(wwwRootPath + "/uploads/", fileName);
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await model.ImgFile.CopyToAsync(fileStream);
                    }

                    imgPath = "/uploads/" + model.ImgFile.FileName;
                }

                var oProduct = ctx.ProductA.Where(w => w.ProductId == model.ProductId).FirstOrDefault();
                if (oProduct != null)
                {
                    oProduct.ProductName = model.ProductName;
                    oProduct.Quantity = model.Quantity;
                    oProduct.Price = model.Price;
                    oProduct.ExpireDate = model.ExpireDate;
                    oProduct.CategoryId = model.CategoryId;
                    if (!string.IsNullOrEmpty(imgPath))
                    {
                        string wwwRootPath = _hostEnvironment.WebRootPath;
                        var fileName = Path.GetFileName(oProduct.ImagePath);
                        string fileLocation = Path.Combine(wwwRootPath + "/uploads/", fileName);
                        if (System.IO.File.Exists(fileLocation))
                        {
                            System.IO.File.Delete(fileLocation);
                        }
                    }
                    oProduct.ImagePath = imgPath == "" ? oProduct.ImagePath : imgPath;

                    ctx.SaveChanges();
                }

                return RedirectToAction("Index");
            }

            public IActionResult EditMultiple(int id)
            {
                var ctx = _context;
                var oCategoryWiseProduct = new VmCategoryWiseProduct();
                var listProduct = (from p in ctx.ProductA
                                   join c in ctx.Categories on p.CategoryId equals c.CategoryId
                                   where p.CategoryId == id
                                   select new VmProduct
                                   {
                                       CategoryId = p.CategoryId,
                                       CategoryName = c.CategoryName,
                                       ExpireDate = p.ExpireDate,
                                       ImagePath = p.ImagePath,
                                       Price = p.Price,
                                       ProductId = p.ProductId,
                                       ProductName = p.ProductName,
                                       Quantity = p.Quantity
                                   }).ToList();

CoreProjectRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreProjectRole</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link href="~/lib/bootstrap/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-reboot.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">   
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreProjectRole</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @{ if (User.Identity.IsAuthenticated)
                                        {
                                            List<CoreProjectRole.ViewModels.Menu> menus = CoreProjectRole.Data.RolesForMenu.GetMenus(User.Identity.Name);
                                            foreach (CoreProjectRole.ViewModels.Menu menu in menus)
                                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="@menu.ControllerName" asp-action="@menu.ActionName">@menu.RoleName</a>
                            </li> }
                                            if (User.IsInRole("Admin"))
                                            {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                            </li>
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserRole" asp-action="Index">User Role</a>
                                                </li>

                                                                                        <li class="nav-item">
                                                                                            <a class="nav-link text-dark" asp-area="" asp-controller="MyProduct" asp-action="Index">View Models</a>
                                                                                        </li>
                                                                                        <li class="nav-item">
                                                                                            <a class="nav-link text-dark" asp-area="" asp-controller="MyHome" asp-action="Index">Mam</a>
                                                                                        </li>
                                                                                        
                                                                                        <li class="nav-item">
                                                                                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">SirSPA</a>
                                                                                        </li>
                                                                                        <li class="nav-item">
                                                                                            <a class="nav-link text-dark" asp-area="" asp-controller="AjaxCrud" asp-action="Index">Ajax Crud</a>
                                                                                        </li>}
                                                                                                    } }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2021 - CoreProjectRole - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CoreProjectRole/Views/Shared/_PlayerDetailsPartial.cshtml
@model CoreProjectRole.ViewModels.PlayerListViewModel
@{
    var photoPath = "/Images/" + (Model.ImageUrl ?? "no.png");
}
<div>
    <h4>Player Details</h4>
    <h2 style="font-family:Algerian; text-align:center; color:black;">Player Details</h2>
    <div class="container" style="background-color:#18ffff">
        <br />
        <table class="table table-bordered">
            <tr>
                <th>Player ID</th>
                <td>@Html.DisplayFor(p => p.PlayerID)</td>
            </tr>
            <tr>
                <th>Player Name</th>
                <td>@Html.DisplayFor(p => p.Name)</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@Html.DisplayFor(p => p.Email)</td>
            </tr>
            <tr>
                <th>Date of Birth</th>
                <td>@Html.DisplayFor(p => p.DoB)</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>@Html.DisplayFor(p => p.Phone)</td>
            </tr>
            <tr>
                <th>Team</th>
                <td>@Html.DisplayFor(p => p.Team)</td>
            </tr>
            <tr>
                <th>Salary</th>
                <td>@Html.DisplayFor(p => p.Salary)</td>
            </tr>
            <tr>
                <th>Image</th>
                <th><img src="@photoPath" width="75" height="80" /></th>
            </tr>

        </table>
    </div>
</div>